### ISSUE TITLE
Entering Emoji+ keyboard's settings fails / its gear icon is misplaced

### ISSUE THREAD

**Issue by Olf0** [a-dekker/the-emoji-keyboard#1]
I just discovered that ~~I cannot enter~~ the settings of **Emoji+ keyboard** 0.4.3-8 (per the gear icon in the upper right corner of the Emoji+ keyboard) on all of my SailfishOS devices *(Edit) has issues*.
The actual behaviour differs, though:
* On a Jolla 1 under SailfishOS 2.2.1 the gear icon is misplaced downwards, but becomes highlighted when tapping on it ~~(although no settings page is opened, then)~~ *(Edit) and opens when pressed long enough*: ![Screenshot_20190419_002](https://user-images.githubusercontent.com/16547876/56435192-e0c4df00-62d7-11e9-87eb-c0098df651df.png)
* On an Xperia X under SailfishOS 3.0.2 the gear icon is correctly placed (well, almost), but does not become highlighted when pressed *(Edit) and fails to open, no matter how long or often I tap on the gear icon*: ![Screenshot_20190419_001](https://user-images.githubusercontent.com/16547876/56435362-76606e80-62d8-11e9-83a5-8df3cad17362.png)

This issue may have been introduced by the change "Config button fix for Sailfish 3.0.2.8" in v0.4.3-6, as I have not tried entering its settings page ever since updating to v0.4.3-6 (until now with v0.4.3-8).

**Comment by a-dekker** [comment]
If you didn't upgrade to the latest SailfishOS version you should not install the latest version of the Emoji+  keyboard. If people do not want to upgrade their OS version they should pin a version that works. Of course dependencies can be put in the package, but I don't want to encourage people to use old and maybe insecure OS software ;)

The config button was placed outside the keyboard in the latest SailfishOS release, making it unusable. Now it is back on the keyboard, but it's sensitiveness is sub par so to speak, I agree. You have to tap and hold your finger on the lower part of the button, most of the time it takes a few attempts.

It's not a key one would use often (nobody seem to have noticed that the config key was no longer usable), and for now it is at least working (although not perfectly). If I find a way to improve the responsiveness I fix it.

**Comment by Olf0** [comment]
> If you didn't upgrade to the latest SailfishOS version you should not install the latest version of the Emoji+ keyboard. If people do not want to upgrade their OS version they should pin a version that works. Of course dependencies can be put in the package, but I don't want to encourage people to use old and maybe insecure OS software ;)

Oh, this implies that you expect every user to individually detect an issue and then downgrade consecutively through the latest releases until a working version is found to "pin" that version, where "pinning" actually translates into "ignoring the updates offered by your OpenRepos client app".
IMO this is hardly feasible for an average user and only the maintainer of a software knows technically well, when non-backward compatible changes are introduced, hence this should be handled by depending on SailfishOS versions. 

> The config button was placed outside the keyboard in the latest SailfishOS release, making it unusable. Now it is back on the keyboard, but it's sensitiveness is sub par so to speak, I agree. You have to tap and hold your finger on the lower part of the button, most of the time it takes a few attempts.

I really cannot get it to work on the Xperia X under SFOS 3.0.2, no matter what I try.
This works flawlessly (when patient enough, i.e. pressing the gear icon long enough) with the same version (0.4.3.-8) on the Jolla 1 under SFOS 2.2.1 (I can live with the misplaced icon, as long as it is working).

> It's not a key one would use often (nobody seem to have noticed that the config key was no longer usable), and for now it is at least working (although not perfectly).

Well, not for me.

> If I find a way to improve the responsiveness I fix it.

Thanks.

**Comment by a-dekker** [comment]
> Oh, this implies that you expect every user to individually detect an issue and then downgrade consecutively through the latest releases until a working version is found to "pin" that version, where "pinning" actually translates into "ignoring the updates offered by your OpenRepos client app".
> IMO this is hardly feasible for an average user and only the maintainer of a software knows technically well, when non-backward compatible changes are introduced, hence this should be handled by depending on SailfishOS versions in the spec file or by handling the different cases in the code.
> 
No, people should just get their OS up to date, just like is strongly advised for your desktop OS. Safer for the user and easier to maintain for developers. Just my 2 cents.

> I really cannot get it to work on the Xperia X under SFOS 3.0.2, no matter what I try.
> This works flawlessly (when patient enough, i.e. pressing the gear icon long enough) with the same version (0.4.3-8) on the Jolla 1 under SFOS 2.2.1 (I can live with the misplaced icon, as long as it is working).
> 
> > It's not a key one would use often (nobody seem to have noticed that the config key was no longer usable), and for now it is at least working (although not perfectly).
> 
> Well, not for me.
> 
I do not have magic fingers afaik, but it works all of my devices, including the Xperia X.

**Comment by Olf0** [comment]
Yes, even with my unmagic fingers I finally managed to open the settings page once on the Xperia X by patiently tapping on the lower border of the rectangle enclosing the gear symbol.

**Comment by Olf0** [comment]
I have been playing around with this a bit.
The root cause is that emojiKeyboard.height excludes the configRow before SailfishOS 3(.0.2?), but includes it later.
I have not yet found where emojiKeyboard.height is set, but supposedly a proper fix should be introduced there.

Additionally (in custom_emoji/EmojiConfigRow.qml), parent.height (configRow) and configRow.height seem to stay 0 rsp. false, even if the configRow is visible (e.g., because configVisible seems to stay false; have not checked this theory though).

Consequently, with emojiKeyboard.height assigned to different values on SFOS 2 and 3, the button position is fine (supposedly "as intended") with:
- On SFOS 2:
  y: -emojiKeyboard.height - Theme.itemSizeSmall + Theme.paddingSmall
- On SFOS 3:
  y: -emojiKeyboard.height + Theme.paddingSmall

But that is just a simplified workaround, rectifying emojiKeyboard.height to be assigned to a consistent value (regardless of the SFOS version) would be much better, IMO.

**Comment by Olf0** [comment]
And while above change simpliies the calculation of the horizontal position, I completely fail to open the settings on SFOS 3.0.2 (again).
Adding a - configRow.height or a - parent.height makes no difference (as expected).

But the real configRow.height / parent.height always seems to be Theme.itemSizeSmall

**Comment by a-dekker** [comment]
Latest release should fix the responsiveness issue

**Comment by Olf0** [comment]
Thank you, now (with disabled z=-1 in v0.4.3-9) entering the settings is working flawlessly under SFOS 3.0.2.
